apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'pushgateway'
        static_configs:
          - targets: ['prometheus-prometheus-pushgateway:9091']
